name: Autograding Tests

on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test_main.py
      id: test_main-py
      uses: education/autograding-command-grader@v1
      with:
        test-name: test_main.py
        setup-command: sudo -H pip3 install pytest
        command: pytest -v test_main.py
        timeout: 10
        max-score: 40
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        TEST_MAIN-PY_RESULTS: "${{steps.test_main-py.outputs.result}}"
      with:
        runners: test_main-py